/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LegalMatterType = IDL.Variant({
  'other' : IDL.Null,
  'civil' : IDL.Null,
  'criminal' : IDL.Null,
  'property' : IDL.Null,
  'corporate' : IDL.Null,
  'family' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'matterType' : LegalMatterType,
});
export const Testimonial = IDL.Record({
  'starRating' : IDL.Nat,
  'clientName' : IDL.Text,
  'reviewText' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTestimonialsByRating' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LegalMatterType],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LegalMatterType = IDL.Variant({
    'other' : IDL.Null,
    'civil' : IDL.Null,
    'criminal' : IDL.Null,
    'property' : IDL.Null,
    'corporate' : IDL.Null,
    'family' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'matterType' : LegalMatterType,
  });
  const Testimonial = IDL.Record({
    'starRating' : IDL.Nat,
    'clientName' : IDL.Text,
    'reviewText' : IDL.Text,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTestimonialsByRating' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LegalMatterType],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };